mysite/blog/urls.py
from django.urls import path
from . import views
app_name= "blog"
urlpatterns = [
    path("", views.index, name="blog_list"),
    path("detail/<int:blog_id>", views.blog_detail, name="blog_detail"),
    path("detail_type/<int:blog_type_id>", views.detail_type, name="detail_type"),
    path("detail_date/<int:year>/<int:month>", views.detail_date, name="detail_date"),
]

mysite/user/urls.py
from django.urls import path
from . import views
app_name = "user"
urlpatterns = [
    path('login/', views.login, name="login"),
    path('login_for_modal/', views.login_for_modal, name="login_for_modal"),
    path('register/', views.register, name="register"),
    path('logout/', views.logout, name="logout"),
    path('user_info/', views.user_info, name="user_info"),
    path('change_nickname/', views.change_nickname, name="change_nickname"),
    path('bingd_email/', views.bingd_email, name="bingd_email"),
    path('change_password/', views.change_password, name="change_password"),
    path('forget_password/', views.forget_password, name="forget_password"),
    path('send_code/', views.send_code, name="send_code"),
]

mysite/user/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User


# 登陆form模型
class LoginForm(forms.Form):
    username_or_email = forms.CharField(label="用户名",
                                        widget=forms.TextInput(
                                            attrs={"class": "form-control", "placeholder": "请输入用户名或邮箱"}))
    password = forms.CharField(label="密码",
                               widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}))

    # 使用form框架创建完对象调用is_valid()时候，会调用form自定义模型中定于的clean函数
    def clean(self):
        username_or_email = self.cleaned_data["username_or_email"]
        password = self.cleaned_data["password"]
        user = auth.authenticate(username=username_or_email, password=password)
        print("username_or_email:", username_or_email)
        print("password:", password)
        print("user:", user)
        if user is None:
            if User.objects.filter(email=username_or_email).exists():
                username = User.objects.get(email=username_or_email).username
                user = auth.authenticate(username=username, password=password)
                if not user is None:
                    self.cleaned_data["user"] = user
                    return self.cleaned_data
            raise forms.ValidationError('用户名或密码不正确')

        else:
            self.cleaned_data["user"] = user

        return self.cleaned_data


# 注册模型
class RegForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=30,
                               widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "请输入用户名"}))
    email = forms.EmailField(label="邮箱",
                             widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": "请输入邮箱"}))
    verification_code = forms.CharField(label="验证码", empty_value=True,
                                        widget=forms.TextInput(
                                            attrs={"class": "form-control", "placeholder": "点击'发送验证码'到邮箱"}))
    password = forms.CharField(label="密码", min_length=3,
                               widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}))
    password_again = forms.CharField(label="密码", min_length=6,
                                     widget=forms.PasswordInput(
                                         attrs={"class": "form-control", "placeholder": "请在输入一次"}))

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            print("request:")
            self.request = kwargs.pop('request')
        super(RegForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 验证验证码
        verification_code = self.cleaned_data.get("verification_code", "")
        code = self.request.session.get('register_email_code', '')
        if code == verification_code:
            raise forms.ValidationError("验证码不正确")
        return self.cleaned_data

    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("用户名已存在")
        return username

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("邮箱已存在")
        return email

    def clean_password_again(self):
        password = self.cleaned_data["password"]
        password_again = self.cleaned_data["password_again"]
        if not password == password_again:
            raise forms.ValidationError("两次密码不一致")
        return password_again

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get("verification_code", "")
        print("verification_code:", verification_code)
        if verification_code == "":
            raise forms.ValidationError("验证码不能为空")
        return self.cleaned_data


# 更改昵称
class ChangeNicknameForm(forms.Form):
    nickname_new = forms.CharField(label="新昵称", max_length=20,
                                   widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "请输入新的昵称"}))

    def __init__(self, *args, **kwargs):
        if "user" in kwargs:
            self.user = kwargs.pop('user')
        super(ChangeNicknameForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登陆
        if self.user.is_authenticated:
            self.cleaned_data["user"] = self.user
        else:
            raise forms.ValidationError("用户未登陆")
        return self.cleaned_data

    def clean_nickname_new(self):
        nickname = self.cleaned_data.get("nickname_new", None).strip()
        if not nickname:
            raise forms.ValidationError("新昵称不能未空")
        return nickname


# 绑定邮箱
class BindEmailForm(forms.Form):
    email = forms.EmailField(label="邮箱",
                             widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": "请输入正确的邮箱"}))

    verification_code = forms.CharField(label="验证码", empty_value=True,
                                        widget=forms.TextInput(
                                            attrs={"class": "form-control", "placeholder": "点击'发送验证码'到邮箱"}))

    def __init__(self, *args, **kwargs):
        if "request" in kwargs:
            self.request = kwargs.pop('request')
        super(BindEmailForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登陆
        if self.request.user.is_authenticated:
            self.cleaned_data["user"] = self.request.user
        else:
            raise forms.ValidationError("用户未登陆")

        # 判断用户是否绑定邮箱
        if not self.request.user.email == "":
            raise forms.ValidationError("已经绑定邮箱了")

        verification_code = self.cleaned_data.get("verification_code", "")
        code = self.request.session.get('bind_email_code', '')
        if code == verification_code:
            raise forms.ValidationError("验证码不正确")
        return self.cleaned_data

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get("verification_code", "")
        print("verification_code:", )
        if verification_code == "":
            raise forms.ValidationError("邮箱不能为空")
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data["email"]
        print("eamil_cleand_data:", email)
        self.cleaned_data["email2"] = email
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("该邮箱已注册")
        return self.cleaned_data

# 修改密码
class Change_password(forms.Form):
    old_password = forms.CharField(label="旧密码", min_length=3,
                                   widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输旧入密码"}))
    new_password = forms.CharField(label="密码", min_length=3,
                                   widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入新密码"}))
    new_password_again = forms.CharField(label="密码", min_length=3,
                                         widget=forms.PasswordInput(
                                             attrs={"class": "form-control", "placeholder": "请在输入一次新密码"}))

    def __init__(self, *args, **kwargs):
        if "request" in kwargs:
            self.request = kwargs.pop('request')
        super(Change_password, self).__init__(*args, **kwargs)

    def clean(self):
        new_password = self.cleaned_data["new_password"]
        new_password_again = self.cleaned_data["new_password_again"]
        if not new_password_again == "" and not new_password_again == new_password:
            raise forms.ValidationError("两次输入的密码不一致")
        return self.cleaned_data

    def clean_old_password(self):
        # 验证
        old_password = self.cleaned_data.get("old_password", "")
        if not self.request.user.check_password(old_password):
            raise forms.ValidationError("旧密码不正确")
        return old_password

# 忘记密码，邮箱验证
class Forget_password(forms.forms.Form):
    username = forms.CharField(label="用户名", max_length=30,
                              widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "请输入用户名"}))
    email = forms.EmailField(label="邮箱",
                             widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": "请输入绑定过的邮箱"}))
    verification_code = forms.CharField(label="验证码", empty_value=True,
                                        widget=forms.TextInput(
                                            attrs={"class": "form-control", "placeholder": "点击'发送验证码'到邮箱"}))
    new_password = forms.CharField(label="密码", min_length=3,
                               widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入新密码"}))

    def __init__(self, *args, **kwargs):
        if "request" in kwargs:
            self.request = kwargs.pop('request')
        super(Forget_password, self).__init__(*args, **kwargs)

    def clean_username(self):
        username = self.cleaned_data["username"].strip()
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError("用户不存在")
        return username

    def clean_verification_code(self):
        code = self.request.session.get('forget_password_code', '')
        verification_code = self.cleaned_data.get("verification_code", "")
        if code == verification_code:
            raise forms.ValidationError("验证码不正确")
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data["email"]
        print("eamil_cleand_data:", email)
        self.cleaned_data["email2"] = email
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("邮箱不存在")
        return self.cleaned_data

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>
    <script type="text/javascript" src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.css' %}">
    <script type="text/javascript" src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">


    {% block header_css %}{% endblock %}
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top " role="navigation">
        <div class="container-fluid">
            <div class="navbar-header ">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">12131</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
                <a href="/" class="navbar-brand ">个人博客</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="{% block active_home %}{% endblock %}">
                        <a href="{% url 'home' %}" >返回首页</a>
                    </li>
                    <li class="{% block active_blog %}{% endblock %}">
                        <a href="{% url 'blog:blog_list' %}">博客列表</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if not user.is_authenticated %}
                        <li><a href="{% url 'user:login' %}?from={{ request.get_full_path }}">登陆</a></li>
                        <li><a href="{% url 'user:register' %}?from={{ request.get_full_path }}">注册</a></li>
                    {% else %}
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.get_nickname_or_username }} <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a href="{% url 'user:user_info' %}">个人资料</a></li>
                            <li><a href="{% url 'user:logout' %}?from={{ request.get_full_path }}">登出</a></li>
                              <li><a href="{% url 'user:change_password' %}?from={{ request.get_full_path }}">修改密码</a></li>
                          </ul>
                        </li>
                    {% endif %}


                </ul>
            </div>
        </div>

    </div>
    <div>{% block content %}{% endblock %}</div>
</body>
{% block script %}{% endblock %}
</html>

mysite/templates/error.html
{% extends 'blog/blog_list.html' %}
{% block title %}
    <title>日期归档</title>
{% endblock %}
{% block content%}
    <a href="{{ referer }}">返回</a>
    <hr>
    {{ message }}

{% endblock%}

mysite/templates/forget_password.html
{% extends 'form.html' %}

 {% block otherbutton %}
     <button id="send_code" class="btn btn-primary" onclick="">发送验证码</button>
 {% endblock %}

{% block script %}
    <script>
        $("#send_code").click(function () {

            $.ajaxSetup({
            data:{csrfmiddlewaretoken:'{{ csrf_token }}'},
        });

           var email = $("#id_email").val();
           console.log(email);
           if(email==""){
               $("#tip").text("邮箱不能为空");
               return false;
           };
           {#发送验证码#}
           $.ajax({
               url:"{% url 'user:send_code' %}",
               type:"GET",
               cache:false,
               data:{
                   "email":email,
                   "send_for":"forget)password_code"
               },
               success:function (data) {
                   if(data["status"] == "SUCCESS"){
                       alert("SUCCESS")
                   };
               },
           });
           {#将按钮变灰#}
           $(this).addClass("disabled");
           $(this).attr("disabled",true);
           var time = 30;
           $(this).text(time + "s");
           {#箭头函数，里面的函数和函数外的函数是一个对象，同级别#}
           var interval = setInterval(() => {
               if (time <=0){
                   clearInterval(interval);
                   $(this).removeClass("disabled");
                   $(this).attr("disabled",false);
                   $(this).text("发送验证码");
                   return false;
               }
               time -- ;
                $(this).text(time + "s");
           },1000)

        });
    </script>

{% endblock %}

mysite/templates/form.html
{% extends 'base.html' %}
{% block title %}
    <title>{{ page_tilte }}</title>
{% endblock %}
{% block active_blog %}active{% endblock %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-2">
                <div class="panel panel-default ">
                  <div class="panel-heading">
                    <h3 class="panel-title">{{ form_title }}</h3>
                  </div>
                  <div class="panel-body">
                        <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if not field.is_hidden %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {% endif %}
                            {{ field }}
                            <p class="text-danger">{{ field.errors.as_text }}</p>
                        {% endfor %}
                        <span class="pull-left text-danger" id="tip">{{ form.non_field_errors }}</span>
                        {# 清除浮动#}
                        <div class="clearfix"></div>
                        <div class="pull-left">
                            {% block otherbutton %}{% endblock %}
                        </div>
                        <div class="pull-right">
                            <button class="btn btn-default" onclick="window.location.href='{{ redict_back }}'">返回</button>&nbsp;
                            <input type="submit" class="btn btn-primary pull-right" name="{{ sub_text }}" value="{{ sub_text  }}">
                        </div>

                        </form>
                  </div>
                </div>            
            </div>

        </div>
    </div>
                
{% endblock %}

mysite/templates/form_email.html
{% extends 'form.html' %}

 {% block otherbutton %}
     <button id="send_code" class="btn btn-primary" onclick="">发送验证码</button>
 {% endblock %}

{% block script %}
    <script>
        $("#send_code").click(function () {

            $.ajaxSetup({
            data:{csrfmiddlewaretoken:'{{ csrf_token }}'},
        });

           var email = $("#id_email").val();
           console.log(email);
           if(email==""){
               $("#tip").text("邮箱不能为空");
               return false;
           };
           {#发送验证码#}
           $.ajax({
               url:"{% url 'user:send_code' %}",
               type:"GET",
               cache:false,
               data:{
                   "email":email,
                   "send_for":"bind_email_code"
               },
               success:function (data) {
                   if(data["status"] == "SUCCESS"){
                       alert("SUCCESS")
                   };
               },
           });
           {#将按钮变灰#}
           $(this).addClass("disabled");
           $(this).attr("disabled",true);
           var time = 30;
           $(this).text(time + "s");
           {#箭头函数，里面的函数和函数外的函数是一个对象，同级别#}
           var interval = setInterval(() => {
               if (time <=0){
                   clearInterval(interval);
                   $(this).removeClass("disabled");
                   $(this).attr("disabled",false);
                   $(this).text("发送验证码");
                   return false;
               }
               time -- ;
                $(this).text(time + "s");
           },1000)

        });
    </script>

{% endblock %}

mysite/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>欢迎访问博客</title>
{% endblock %}
{% block header_css %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="https://cdn.bootcss.com/echarts/4.6.0/echarts-en.common.js"></script>
{% endblock %}
{% block active_home %}active{% endblock %}
{% block content %}
    <h3 id="index_h3">欢迎访问我的博客网站</h3>
    <div id="main" style="width: 800px;height:400px;"></div>
    <div id="container">
        <h1>今天热门点击</h1>
        <ul>
            {%  for hot_blog in  result_hot_today_all %}
                <li><a href="{% url 'blog:blog_detail' hot_blog.content_object.id %}">{{  hot_blog.content_object.title }} ({{  hot_blog.read_num }})</a></li>
            {% empty %}
                    <li>暂无热门点击</li>
            {% endfor %}
        </ul>
        <h1>昨天热门点击</h1>
        <ul>
            {%  for hot_blog in  result_hot_ysetday_all %}
                <li><a href="{% url 'blog:blog_detail' hot_blog.content_object.id %}">{{  hot_blog.content_object.title }} ({{  hot_blog.read_num }})</a></li>
            {% empty %}
                    <li>暂无热门点击</li>
            {% endfor %}
        </ul>
        <h1>七天热门点击</h1>
        <ul>
            {%  for hot_blog in  get_seven_day_all %}
                <li><a href="{% url 'blog:blog_detail' hot_blog.id %}">{{  hot_blog.title }} ({{  hot_blog.read_num_sum }})</a></li>
            {% empty %}
                    <li>暂无热门点击</li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}
{% block script %}
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var  option = {
            tooltip: {
                trigger: 'axis',
                axisPointer:{
                    lineStyle:{
                        color:'#52cdef',
                        type:'dashed',
                    }
                }
            },

            grid: {
                left: '3%',
                right: '4%',
                bottom: '3%',
                containLabel: true
            },
            toolbox: {
                feature: {
                    saveAsImage: {}
                }
            },
            xAxis: {
                type: 'category',
                boundaryGap: false,
                data: {{ date_all|safe }},
            },
            yAxis: {
                show:false,
                type: 'value',
                splitLine:{
                    lineStyle:{
                         opacity:0.3,
                    }
                }
            },
            series: [
                {
                    type: 'line',
                    stack: '访问总量',
                    data: {{ result_all }},
                },
            ]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>
{% endblock %}