mysite/blog/urls.py
from django.urls import path
from . import views
app_name= "blog"
urlpatterns = [
    path("", views.index, name="blog_list"),
    path("detail/<int:blog_id>", views.blog_detail, name="blog_detail"),
    path("detail_type/<int:blog_type_id>", views.detail_type, name="detail_type"),
    path("detail_date/<int:year>/<int:month>", views.detail_date, name="detail_date"),
]

mysite/user/urls.py
from django.urls import path
from . import views
app_name = "user"
urlpatterns = [
    path('login/', views.login, name="login"),
    path('login_for_modal/', views.login_for_modal, name="login_for_modal"),
    path('register/', views.register, name="register"),
    path('logout/', views.logout, name="logout"),
    path('user_info/', views.user_info, name="user_info"),
    path('change_nickname/', views.change_nickname, name="change_nickname"),
    path('bingd_email/', views.bingd_email, name="bingd_email"),
    path('change_password/', views.change_password, name="change_password"),
    path('forget_password/', views.forget_password, name="forget_password"),
    path('send_code/', views.send_code, name="send_code"),
]

mysite/user/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User


# 登陆form模型
class LoginForm(forms.Form):
    username_or_email = forms.CharField(label="用户名",
                                        widget=forms.TextInput(
                                            attrs={"class": "form-control", "placeholder": "请输入用户名或邮箱"}))
    password = forms.CharField(label="密码",
                               widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}))

    # 使用form框架创建完对象调用is_valid()时候，会调用form自定义模型中定于的clean函数
    def clean(self):
        username_or_email = self.cleaned_data["username_or_email"]
        password = self.cleaned_data["password"]
        user = auth.authenticate(username=username_or_email, password=password)
        print("username_or_email:", username_or_email)
        print("password:", password)
        print("user:", user)
        if user is None:
            if User.objects.filter(email=username_or_email).exists():
                username = User.objects.get(email=username_or_email).username
                user = auth.authenticate(username=username, password=password)
                if not user is None:
                    self.cleaned_data["user"] = user
                    return self.cleaned_data
            raise forms.ValidationError('用户名或密码不正确')

        else:
            self.cleaned_data["user"] = user

        return self.cleaned_data


# 注册模型
class RegForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=30,
                               widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "请输入用户名"}))
    email = forms.EmailField(label="邮箱",
                             widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": "请输入邮箱"}))
    verification_code = forms.CharField(label="验证码", empty_value=True,
                                        widget=forms.TextInput(
                                            attrs={"class": "form-control", "placeholder": "点击'发送验证码'到邮箱"}))
    password = forms.CharField(label="密码", min_length=3,
                               widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}))
    password_again = forms.CharField(label="密码", min_length=6,
                                     widget=forms.PasswordInput(
                                         attrs={"class": "form-control", "placeholder": "请在输入一次"}))

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            print("request:")
            self.request = kwargs.pop('request')
        super(RegForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 验证验证码
        verification_code = self.cleaned_data.get("verification_code", "")
        code = self.request.session.get('register_email_code', '')
        if code == verification_code:
            raise forms.ValidationError("验证码不正确")
        return self.cleaned_data

    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("用户名已存在")
        return username

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("邮箱已存在")
        return email

    def clean_password_again(self):
        password = self.cleaned_data["password"]
        password_again = self.cleaned_data["password_again"]
        if not password == password_again:
            raise forms.ValidationError("两次密码不一致")
        return password_again

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get("verification_code", "")
        print("verification_code:", verification_code)
        if verification_code == "":
            raise forms.ValidationError("验证码不能为空")
        return self.cleaned_data


# 更改昵称
class ChangeNicknameForm(forms.Form):
    nickname_new = forms.CharField(label="新昵称", max_length=20,
                                   widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "请输入新的昵称"}))

    def __init__(self, *args, **kwargs):
        if "user" in kwargs:
            self.user = kwargs.pop('user')
        super(ChangeNicknameForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登陆
        if self.user.is_authenticated:
            self.cleaned_data["user"] = self.user
        else:
            raise forms.ValidationError("用户未登陆")
        return self.cleaned_data

    def clean_nickname_new(self):
        nickname = self.cleaned_data.get("nickname_new", None).strip()
        if not nickname:
            raise forms.ValidationError("新昵称不能未空")
        return nickname


# 绑定邮箱
class BindEmailForm(forms.Form):
    email = forms.EmailField(label="邮箱",
                             widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": "请输入正确的邮箱"}))

    verification_code = forms.CharField(label="验证码", empty_value=True,
                                        widget=forms.TextInput(
                                            attrs={"class": "form-control", "placeholder": "点击'发送验证码'到邮箱"}))

    def __init__(self, *args, **kwargs):
        if "request" in kwargs:
            self.request = kwargs.pop('request')
        super(BindEmailForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登陆
        if self.request.user.is_authenticated:
            self.cleaned_data["user"] = self.request.user
        else:
            raise forms.ValidationError("用户未登陆")

        # 判断用户是否绑定邮箱
        if not self.request.user.email == "":
            raise forms.ValidationError("已经绑定邮箱了")

        verification_code = self.cleaned_data.get("verification_code", "")
        code = self.request.session.get('bind_email_code', '')
        if code == verification_code:
            raise forms.ValidationError("验证码不正确")
        return self.cleaned_data

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get("verification_code", "")
        print("verification_code:", )
        if verification_code == "":
            raise forms.ValidationError("邮箱不能为空")
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data["email"]
        print("eamil_cleand_data:", email)
        self.cleaned_data["email2"] = email
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("该邮箱已注册")
        return self.cleaned_data

# 修改密码
class Change_password(forms.Form):
    old_password = forms.CharField(label="旧密码", min_length=3,
                                   widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输旧入密码"}))
    new_password = forms.CharField(label="密码", min_length=3,
                                   widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入新密码"}))
    new_password_again = forms.CharField(label="密码", min_length=3,
                                         widget=forms.PasswordInput(
                                             attrs={"class": "form-control", "placeholder": "请在输入一次新密码"}))

    def __init__(self, *args, **kwargs):
        if "request" in kwargs:
            self.request = kwargs.pop('request')
        super(Change_password, self).__init__(*args, **kwargs)

    def clean(self):
        new_password = self.cleaned_data["new_password"]
        new_password_again = self.cleaned_data["new_password_again"]
        if not new_password_again == "" and not new_password_again == new_password:
            raise forms.ValidationError("两次输入的密码不一致")
        return self.cleaned_data

    def clean_old_password(self):
        # 验证
        old_password = self.cleaned_data.get("old_password", "")
        if not self.request.user.check_password(old_password):
            raise forms.ValidationError("旧密码不正确")
        return old_password

# 忘记密码，邮箱验证
class Forget_password(forms.forms.Form):
    username = forms.CharField(label="用户名", max_length=30,
                              widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "请输入用户名"}))
    email = forms.EmailField(label="邮箱",
                             widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": "请输入绑定过的邮箱"}))
    verification_code = forms.CharField(label="验证码", empty_value=True,
                                        widget=forms.TextInput(
                                            attrs={"class": "form-control", "placeholder": "点击'发送验证码'到邮箱"}))
    new_password = forms.CharField(label="密码", min_length=3,
                               widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入新密码"}))

    def __init__(self, *args, **kwargs):
        if "request" in kwargs:
            self.request = kwargs.pop('request')
        super(Forget_password, self).__init__(*args, **kwargs)

    def clean_username(self):
        username = self.cleaned_data["username"].strip()
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError("用户不存在")
        return username

    def clean_verification_code(self):
        code = self.request.session.get('forget_password_code', '')
        verification_code = self.cleaned_data.get("verification_code", "")
        if code == verification_code:
            raise forms.ValidationError("验证码不正确")
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data["email"]
        print("eamil_cleand_data:", email)
        self.cleaned_data["email2"] = email
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("邮箱不存在")
        return self.cleaned_data

mysite/user/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.urls import reverse
from .forms import LoginForm, RegForm, ChangeNicknameForm, BindEmailForm,Change_password,Forget_password
from django.contrib.auth.models import User
from django.http.response import JsonResponse
from .models import Profile
from mysite.settings_base import EMAIL_HOST_USER
import hashlib, datetime


# Create your views here.
# 登陆
def login(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user = login_form.cleaned_data["user"]
            auth.login(request, user)
            return redirect(request.GET.get("from", reverse("home")))
        return render(request, "user/login.html", locals())
    else:
        login_form = LoginForm()
    return render(request, "user/login.html", locals())


# 模态框登陆验证
def login_for_modal(request):
    print("login_for_modal")
    login_form = LoginForm(request.POST)
    data = {}
    if login_form.is_valid():
        user = login_form.cleaned_data["user"]
        auth.login(request, user)
        data["status"] = "SUCCESS"
    else:
        data["status"] = "ERROE"
    print("data:", data)
    return JsonResponse(data)


# 注册用户
def register(request):
    print('request.GET.get("from", reverse("home")):', request.GET.get("from", reverse("home")))
    if request.method == "POST":
        reg_form = RegForm(request.POST, request=request)
        if reg_form.is_valid():
            username = reg_form.cleaned_data["username"]
            password = reg_form.cleaned_data["password"]
            email = reg_form.cleaned_data["email"]
            # 创建用户
            user = User.objects.create_user(username, email, password)
            user.save()
            # 删除session
            del request.session["register_email_code"]
            # 登陆用户
            user = auth.authenticate(username=username, password=password)
            auth.login(request, user)
            return redirect(request.GET.get("from", reverse("home")))
    else:
        reg_form = RegForm()
    return render(request, "user/register.html", locals())


# 等出
def logout(request):
    auth.logout(request)
    from_url = request.GET.get("from")
    if "user_info" in from_url:
        return redirect(reverse("home"))
    return redirect(request.GET.get("from"))


def user_info(request):
    return render(request, "user/user_info.html", locals())


# 修改昵称
def change_nickname(request):
    redirect_to = request.GET.get("from", reverse("home"))
    if request.method == "POST":
        form = ChangeNicknameForm(request.POST, user=request.user)
        if form.is_valid():
            nickname_new = form.cleaned_data["nickname_new"]
            profile, new = Profile.objects.get_or_create(user=request.user)
            profile.nickname = nickname_new
            profile.save()
            return redirect(redirect_to)

    else:
        form = ChangeNicknameForm()
    context = {}
    context["form"] = form
    context["page_title"] = "修改昵称"
    context["form_title"] = "修改昵称"
    context["sub_text"] = "提交修改"
    context["redirect_back"] = redirect_to
    return render(request, "form.html", context)


# 绑定邮箱
def bingd_email(request):
    redirect_to = request.GET.get("from", reverse("home"))
    if request.method == "POST":
        form = BindEmailForm(request.POST, request=request)
        if form.is_valid():
            email = form.cleaned_data["email"]
            email2 = form.cleaned_data["email2"]
            print("email:",email)
            print("email2:",email2)
            request.user.email = email2
            request.user.save()
            # 删除session
            del request.session["send_email_code"]
            return redirect(redirect_to)
    else:
        form = BindEmailForm()
    context = {}
    context["form"] = form
    context["page_title"] = "绑定邮箱"
    context["form_title"] = "绑定邮箱1"
    context["sub_text"] = "绑定"
    context["redirect_back"] = redirect_to
    return render(request, "form_email.html", context)

# 更改密码
def change_password(request):
    redirect_to = reverse("home")
    if request.method == "POST":
        form = Change_password(request.POST, request=request)
        if form.is_valid():
            user= request.user
            new_password = form.cleaned_data["new_password"]
            user.set_password(new_password)
            request.user.save()
            logout(request)
            return redirect(reverse("home"))
    else:
        form = Change_password()
    context = {}
    context["form"] = form
    context["page_title"] = "修改密码"
    context["form_title"] = "修改密码"
    context["sub_text"] = "修改"
    context["redirect_back"] = redirect_to
    return render(request, "form.html", context)
def hash_code(value, alt="mysite"):
    h = hashlib.sha256()
    value += alt
    h.update(value.encode())
    return h.hexdigest()


def send_code(request):
    # print("email:", email)
    send_for = request.GET.get("send_for","")
    print("send_for:",send_for)
    email = request.GET.get("email")
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    code = hash_code(email, now)
    data = {}
    print("email:", email)
    if not email == "":
        from django.core.mail import EmailMultiAlternatives

        subject = '来自个人博客的注册确认邮件'
        print("发送成功")
        print("email:", email)
        text_content = '''感谢把绑定邮箱，如果你看到这条消息，说明你的邮箱服务器不提供HTML链接功能，请联系管理员！'''
        html_content = '''<p>感谢绑定</p>你的验证码为{}" '''.format(code)
        msg = EmailMultiAlternatives(subject, text_content, EMAIL_HOST_USER, [email])
        msg.attach_alternative(html_content, "text/html")
        msg.send()
        request.session[send_for] = code
        data["status"] = "SUCCESS"
        return JsonResponse(data)
    else:
        data["status"] = "ERROR"
        return JsonResponse(data)


# 忘记密码
def forget_password(request):
    redirect_to = reverse("home")
    if request.method == "POST":
        form = Forget_password(request.POST, request=request)
        if form.is_valid():
            username = form.cleaned_data["username"]
            new_password = form.cleaned_data["new_password"]
            user = User.objects.get(username=username)
            user.set_password(new_password)
            user.save()
            return redirect(redirect_to)
    else:
        form = Forget_password()
    context = {}
    context["form"] = form
    context["page_title"] = "忘记密码"
    context["form_title"] = "忘记密码"
    context["sub_text"] = "修改"
    context["redirect_back"] = redirect_to
    return render(request, "forget_password.html", context)

mysite/templates/user/login.html
{% extends 'base.html' %}
{% block title %}
    <title>登陆</title>
{% endblock %}
{% block active_blog %}active{% endblock %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-2">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">登陆</h3>
                  </div>
                  <div class="panel-body">
                        <form action="" method="POST">
                        {% csrf_token %}
                        {% for login in login_form %}
                            <label for="{{ login.id_for_label }}">{{ login.label }}</label>
                            {{ login }}
                            <p class="text-danger">{{ login.errors.as_text }}</p>
                        {% endfor %}
                        <span class=" text-danger">{{ login_form.non_field_errors }}</span>
                        <div class="clearfix"></div>
                            <a class="pull-left" href="{% url 'user:forget_password' %}">忘记密码</a>
                        <input type="submit" class="btn btn-primary pull-right" name="登陆">
                        </form>
                  </div>
                </div>            
            </div>

        </div>
    </div>
                
{% endblock %}

mysite/templates/user/register.html
{% extends 'base.html' %}
{% block title %}
    <title>注册</title>
{% endblock %}
{% block active_blog %}active{% endblock %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-2">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">登陆</h3>
                  </div>
                  <div class="panel-body">
                        <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in reg_form %}
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <p class="text-danger">{{ field.errors.as_text }}</p>
                        {% endfor %}
                        <span class=" text-danger">{{ field.non_field_errors }}</span>
                        <div class="clearfix"></div>
                        <button id="send_code" class="btn btn-primary pull-left" onclick="">发送验证码</button>

                        <input type="submit" class="btn btn-primary pull-right" name="注册" value="注册">
                        </form>
                  </div>
                </div>            
            </div>

        </div>
    </div>
                
{% endblock %}
{% block script %}
    <script>
        $("#send_code").click(function () {

            $.ajaxSetup({
            data:{csrfmiddlewaretoken:'{{ csrf_token }}'},
        });

           var email = $("#id_email").val();
           console.log(email);
           if(email==""){
               $("#tip").text("邮箱不能为空");
               return false;
           };
           {#发送验证码#}
           $.ajax({
               url:"{% url 'user:send_code' %}",
               type:"GET",
               cache:false,
               data:{
                   "email":email,
                   "send_for":"register_email_code"
               },
               success:function (data) {
                   if(data["status"] == "SUCCESS"){
                       alert("SUCCESS")
                   };
               },
           });
           {#将按钮变灰#}
           $(this).addClass("disabled");
           $(this).attr("disabled",true);
           var time = 30;
           $(this).text(time + "s");
           {#箭头函数，里面的函数和函数外的函数是一个对象，同级别#}
           var interval = setInterval(() => {
               if (time <=0){
                   clearInterval(interval);
                   $(this).removeClass("disabled");
                   $(this).attr("disabled",false);
                   $(this).text("发送验证码");
                   return false;
               }
               time -- ;
                $(this).text(time + "s");
           },1000)

        });
    </script>

{% endblock %}

mysite/templates/user/user_info.html
{% extends 'base.html' %}
{% block title %}
    <title>个人信息</title>
{% endblock %}
{% load static %}
{% block active_blog %}active{% endblock %}
{% block header_css %}
    <link rel="stylesheet" href="{% static 'css/blog_list.css' %}">
{% endblock %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-2">
                <h2> {{ user.username}}</h2>
                <ul>
                    <li>昵称:{{ user.get_nickname }} <a href="{% url 'user:change_nickname' %}?from={{ request.get_full_path }}">修改昵称</a></li>
                    <li>邮箱:{% if user.email %} {{ user.email }}{% else %} 暂无邮箱  <a href="{% url 'user:bingd_email' %}?from={{ request.get_full_path }}">绑定邮箱</a>  {%endif%}</li>
                    <li>上次登陆时间:{{ user.last_login|date:"Y:m:d H:n:s" }}</li>
                <li> <a href="{% url 'user:change_password' %}?from={{ request.get_full_path }}">修改密码</a> </li>
                </ul>
            </div>
        </div>
    </div>
    <script>
        {#跳转到首页#}
        {#window.location.href = "/"#}
    </script>
{% endblock %}