mysite/blog/urls.py
from django.urls import path
from . import views
app_name= "blog"
urlpatterns = [
    path("", views.index, name="blog_list"),
    path("detail/<int:blog_id>", views.blog_detail, name="blog_detail"),
    path("detail_type/<int:blog_type_id>", views.detail_type, name="detail_type"),
    path("detail_date/<int:year>/<int:month>", views.detail_date, name="detail_date"),
]

mysite/comment/urls.py
from django.urls import path
from comment import views
app_name= "comment"
urlpatterns = [
    path("update_comment", views.update_comment, name="update_coment"),
]

mysite/likes/urls.py
from django.urls import path
from .models import LikeCount,LikeRecord
from . import views
app_name= "likes"
urlpatterns = [
    path("like_change", views.like_change, name="like_change"),
]

mysite/user/urls.py
from django.urls import path
from . import views
app_name = "user"
urlpatterns = [
    path('login/', views.login, name="login"),
    path('login_for_modal/', views.login_for_modal, name="login_for_modal"),
    path('register/', views.register, name="register"),
    path('logout/', views.logout, name="logout"),
    path('user_info/', views.user_info, name="user_info"),
    path('change_nickname/', views.change_nickname, name="change_nickname"),
    path('bingd_email/', views.bingd_email, name="bingd_email"),
    path('change_password/', views.change_password, name="change_password"),
    path('forget_password/', views.forget_password, name="forget_password"),
    path('send_code/', views.send_code, name="send_code"),
]

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from read_statistics.models import ReadNumExpandMethod
from django.contrib.contenttypes.fields import GenericRelation
from read_statistics.models import ReadDetail
from django.urls import reverse


# Create your models here.
# 博客类型
class Blog_type(models.Model):
    type_name = models.CharField(max_length=15, verbose_name="类型名")
    type_describtion = models.CharField(max_length=200, verbose_name="类型描述")
    type_num = models.IntegerField(default=0, null=True, blank=True, verbose_name="类型号")

    def __str__(self):
        return self.type_name

    class Meta:
        # ordering = ["-c_time"]
        verbose_name = "博客类型"
        verbose_name_plural = "博客类型"


# 博客
class Blog(models.Model, ReadNumExpandMethod):
    title = models.CharField(max_length=30, verbose_name="标题")
    blog_type = models.ForeignKey(Blog_type, on_delete=models.DO_NOTHING, verbose_name="博客类型")
    content = RichTextUploadingField(verbose_name="内容")
    c_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    m_time = models.DateTimeField(auto_now=True, verbose_name="最新修改时间")
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1, verbose_name="作者")
    is_deleted = models.BooleanField(default=False, verbose_name="是否删除")
    read_details = GenericRelation(ReadDetail)

    def get_url(self):
        return reverse("blog:blog_detail", kwargs={"blog_id": self.id})

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-c_time", "title", "m_time"]
        verbose_name = "博客"
        verbose_name_plural = "博客"

# # 博客数量
# class ReadNum(models.Model):
#     readed_num = models.IntegerField(default=0, verbose_name="阅读数量")
#     blog = models.OneToOneField(Blog, on_delete=models.CASCADE, verbose_name="关联博客")
#
#     class Meta:
#         verbose_name = "阅读数量"
#         verbose_name_plural = "阅读数量"

mysite/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from blog.models import Blog, Blog_type
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Count
from read_statistics.utils import get_read_num_once
from user.forms import LoginForm

per_page_blog_num = 7


def get_blog_common_data(request, blog_list):
    # 获取页码参数，get请求
    page_num = request.GET.get("page", 1)
    blog_all_num = blog_list.count()
    blog_type_list = Blog_type.objects.all()
    paginator_blog = Paginator(blog_list, per_page_blog_num)
    blog_list_temp = paginator_blog.get_page(int(page_num))
    blog_list = blog_list_temp.object_list
    page_range = [i for i in range(max(int(page_num) - 2, 1), min(int(page_num) + 2, paginator_blog.num_pages) + 1)]
    # 省略号标签添加
    if page_range[0] - 1 >= 2:
        page_range.insert(1, "...")
    if paginator_blog.num_pages - page_range[-1] >= 2:
        page_range.insert(-1, "...")
    # 首尾页添加
    if not page_range[0] == 1:
        page_range.insert(0, 1)
    if not page_range[-1] == paginator_blog.num_pages:
        page_range.append(paginator_blog.num_pages)

    # 获取博客分类对应的数量
    # 方法一：
    # for blog_type in blog_type_list:
    # blog_type.blog_count = Blog.objects.filter(blog_type=blog_type).count()
    # 方法二
    blog_type_list = Blog_type.objects.annotate(blog_count=Count("blog"))
    # 获取博客日期对应的数量
    context_date = {}
    blog_date_list = Blog.objects.dates("c_time", "month", "DESC")
    for blog_date in blog_date_list:
        context_date[blog_date] = Blog.objects.filter(c_time__year=blog_date.year,
                                                      c_time__month=blog_date.month).count()
    print(context_date)
    return blog_all_num, blog_type_list, paginator_blog, blog_list_temp, blog_list, page_range, context_date


# Create your views here.
def index(request):
    print("request.user:",request.user)
    print("request.user:",request.user.id)
    if not request.user.id:
        print("request.user.id")
    blog_list = Blog.objects.filter(is_deleted=False).order_by("-c_time", "title", "m_time")
    blog_all_num, blog_type_list, paginator_blog, blog_list_temp, blog_list, page_range, context_date = get_blog_common_data(
        request,
        blog_list)
    print("context_date:", context_date)

    return render(request, "blog/blog_list.html", locals())


def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    # 获取key，设置cookie
    key = get_read_num_once(request, blog)
    # 上篇博客
    previous_blog = Blog.objects.filter(c_time__gt=blog.c_time)
    previous_blog = previous_blog.last()
    # 下篇博客
    next_blog = Blog.objects.filter(c_time__lt=blog.c_time)
    next_blog = next_blog.first()

    # 创建form对象并进行初始化
    login_form = LoginForm()
    response = render(request, "blog/detail.html", locals())

    response.set_cookie(key, True)
    return response


def detail_type(request, blog_type_id):
    # 获取页码参数，get请求
    page_num = request.GET.get("page", 1)
    blog_type = get_object_or_404(Blog_type, id=blog_type_id)
    blog_list = Blog.objects.filter(blog_type=blog_type)
    blog_all_num, blog_type_list, paginator_blog, blog_list_temp, blog_list, page_range, context_date = get_blog_common_data(
        request,
        blog_list)

    return render(request, "blog/blog_detail_type.html", locals())


def detail_date(request, year, month):
    # 获取页码参数，get请求
    page_num = request.GET.get("page", 1)
    blog_list = Blog.objects.filter(c_time__year=year, c_time__month=month)
    blog_all_num, blog_type_list, paginator_blog, blog_list_temp, blog_list, page_range, context_date = get_blog_common_data(
        request,
        blog_list)
    blog_date_list = Blog.objects.dates("c_time", "month", "DESC")
    return render(request, "blog/blog_detail_date.html", locals())

mysite/templates/blog/blog_detail_date.html
{% extends 'blog/blog_list.html' %}
{% block title %}
    <title>日期归档</title>
{% endblock %}
{% block blog_list%} 
    <p>日期归档:{{ year }} 年 {{ month }} 月 </p>
    <a href="{% url 'blog:blog_list' %}">所有分类总览</a>
{% endblock%}

mysite/templates/blog/blog_detail_type.html
{% extends 'blog/blog_list.html' %}
{% block title %}
    <title>文章分类详情</title>
{% endblock %}
{% block blog_list%} 
    <p>文章分类详情:{{ blog_list|length }}篇博客</p>
    <a href="{% url 'blog:blog_list' %}">所有分类总览</a>
{% endblock%}

mysite/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load static%}
{% block title %}
    <title>文章列表</title>
{% endblock %}
{% block active_blog %}active{% endblock %}
{% load comment_tags %}
{% load likes_tags %}
{% block header_css %}
    <link rel="stylesheet" href="{% static 'css/blog_list.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sx-9 col-sm-9 col-md-9">
                {% block blog_list%} 

                {% endblock%}
                    {% for blog in blog_list %}
                        <div class="panel panel-default">
                        
                          <div class="panel-heading">
                            <h3 class="panel-title"><a href="{% url 'blog:blog_detail' blog.id%}">{{ blog.title }}</a></h3>
                          </div>
                          <div class="panel-body">
                            <p class="blog-info">
                                 <span class="glyphicon glyphicon-tag"></span><a href="{% url 'blog:detail_type' blog.blog_type.id %}">{{ blog.blog_type }} &nbsp;</a> <p class="glyphicon glyphicon-user">{{ blog.author }} <span class="glyphicon glyphicon-time">{{ blog.c_time|date:"Y-m-d H:n:s" }} <span class="glyphicon glyphicon-eye-open">{{ blog.get_read_num }} <span class="glyphicon glyphicon-certificate">{% get_commment_count blog %}</span> <span class="glyphicon glyphicon-thumbs-up btn"></span>{% get_likes_count blog %}
                            </p>
                            <ul>
                                <li>{{ blog.content|striptags|truncatechars:150 }}</li>
                            </ul>
                          </div>
                        </div>
                    {% empty %}
                            <h3> 暂无文章，敬请期待</h3>
                    {% endfor %}

{#                    分页#}
                    <nav aria-label="Page navigation" class="page_align">
                      <ul class="pagination">
                        {% if blog_list_temp.has_previous %}
                            <li><a href="?page={{ blog_list_temp.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                        {% else %}
                            <li class="disabled" ><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a> </li>
                        {% endif %}
                          {% for page  in page_range %}

                              {% if page == blog_list_temp.number %}
                                  <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                              {% else %}
                                  {% if page == "..." %}
                                      <li><a href="#">{{ page }}</a></li>
                                  {% else %}
                                      <li><a href="?page={{ page }}">{{ page }}</a></li>
                                  {% endif %}
                              {% endif %}
                          {% empty %}
                            <li>1</li>
                          {% endfor %}
                        {% if blog_list_temp.has_next %}
                            <li><a href="?page={{ blog_list_temp.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                        {% else %}
                            <li class="disabled" ><a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a> </li>
                        {% endif %}
                      </ul>
                    <p>博客列表，共有{{ blog_all_num }}篇博客,当前为第{{ blog_list_temp.number }}页</p>
                    </nav>


            </div>
            <div class="hidden-xs col-sm-3 col-md-3">
                <div class="panel panel-default" id="panel-default1">
                  <div class="panel-heading"  >博客分类</div>
                  <div class="panel-body">
                    <ul>
                        {% for blog_type in blog_type_list %}
                            <li><a href="{%url  'blog:detail_type' blog_type.id%}">{{  blog_type.type_name  }} ({{ blog_type.blog_count }})</a>
                            </li>
                        {% empty %}
                            <li>暂无分类</li>
                        {% endfor %}
                    </ul>
                  </div>
                </div>
                <div class="panel panel-default" id="panel-default2">
                  <div class="panel-heading"  >日期归档</div>
                  <div class="panel-body">
                    <ul>
                        {% for blog_date,blog_num in context_date.items %}
                            <li><a href="{% url 'blog:detail_date' blog_date.year blog_date.month  %}">{{  blog_date|date:"Y年m月"  }}({{ blog_num }})</a>
                            </li>
                        {% empty %}
                            <li>暂无日期</li>
                        {% endfor %}
                    </ul>
                  </div>
                </div>
            </div>
        </div>
    </div>

    
{% endblock %}

mysite/templates/blog/detail.html
{% extends 'base.html' %}
{% block title %}
    <title>文章详情</title>
{% endblock %}
{% block active_blog %}active{% endblock %}
{% load static %}
{% load comment_tags %}
{% load likes_tags %}
{% block header_css %}
    <link rel="stylesheet" href="{% static 'css/blog_list.css' %}">
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}
{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-md-10">
            <h2>{{ blog.title }}</h2>
            <ul class="blog_content_ul">
                <li>分类：<a href="">{{ blog.blog_type }}</a></li>
                <li>作者：{{ blog.author }}</li>
                <li>发表日期：{{ blog.c_time|date:"Y-m-d H:n:s" }}</li>
                <li>阅读量：({{ blog.get_read_num }})</li>
                <li>评论数：({% get_commment_count blog %})</li>
            </ul>
            <div class="blog_content_div">{{ blog.content|safe }}</div>
            <div class="like" onclick="likechange(this,'blog',{{ blog.id }})">
                <span class="glyphicon glyphicon-thumbs-up btn {% get_likes_status blog %}"></span>
                <div class="like-num" >{% get_likes_count blog %}</div>
                <div class="like-message">喜欢</div>
            </div>
            <div class="blog_more">

                <p>
                    {% if previous_blog.title %}
                        <a href="">上一篇：{{ previous_blog.title }}</a>
                    {% else %}
                        上一篇：没有了
                    {% endif %}
                </p>
                <p>
                    {% if next_blog.title %}
                        <a href="">下一篇：{{ next_blog.title }}</a>
                    {% else %}
                        下一篇：没有了
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">
            <div class="comment-area">
                <h3 class="comment-area-title">提交评论</h3>
                {% if not  request.user.is_authenticated %}
                    未登录，登陆后可以评论
                    <a href="{% url 'user:login' %}?from={{ request.get_full_path }}" class="btn btn-info">登陆</a>
                    <span> or </span>
                    <a href="{% url 'user:register' %}?from={{ request.get_full_path }}" class="btn btn-success">注册</a>
                {% else %}
                    欢迎评论:{{ user.get_nickname_or_username }}<br>
                    <div id="content-reply-container" style="display:none"><p id="reply_title">回复：</p><div id="comment-reply-bk"></div></div>
                    <form id="comment-form" action="{% url 'comment:update_coment' %}" method="POST"
                          style="overflow: hidden">
                        {% csrf_token %}
                        <div class="form-group">
                        {% get_comment_form blog as content_form %}
                            {% for field in content_form %}
                                {{ field }}
                            {% endfor %}
                        </div>
                        <input class="btn btn-default btn-primary" type="submit" style="float: right;" name="提交评论">
                        <span class="text-danger" id="comment_error"></span>
                    </form>

                {% endif %}
            </div>
            <div class="comment-area">
                <h3 class="comment-area-title">显示评论区</h3>
                <ul id="comment-list">
                    {% get_comments blog as conments %}
                    {% for comment in conments %}
                        <div class="conment-root" id="{{ comment.id }}">
                            <li id="{{ comment.id  }}">{{ comment.usr.get_nickname_or_username }}({{ comment.comment_time|date:"Y年-m月-d日" }})
                                : <div id="comment_{{ comment.id }}">{{ comment.text|safe }}</div></li>
                            <a href="javascript:reply_comment({{ comment.id }})">回复</a>
                                <div class="like" onclick="likechange(this,'comment',{{ comment.id }})">
                                    <span class="glyphicon glyphicon-thumbs-up btn {% get_likes_status comment %}" id="like-btn"></span>
                                    <div class="like-num">{% get_likes_count comment %}</div>
                                </div>

                            {% for reply in comment.root_comment.all %}
                                <div class="comment-reply">
                                    <li >{{ reply.usr.get_nickname_or_username }}({{ reply.comment_time|date:"Y年-m月-d日" }})
                                        回复 {{ comment.usr.get_nickname_or_username }}(内容：{{ reply.parent.text }})
                                        : <div id="comment_{{ reply.id }}">{{ reply.text|safe }}</div></li>
                                    <a href="javascript:reply_comment({{ reply.id }})"> 回复</a>
                                     <div class="like" onclick="likechange(this,'comment',{{ reply.id }})">
                                        <span class="glyphicon glyphicon-thumbs-up btn {% get_likes_status reply %}" id="like-btn"></span>
                                        <div class="like-num" >{% get_likes_count reply %}</div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% empty %}
                        <li>暂时无评论</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{#    登录模态框#}
    <div class="modal fade" id="login_model" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <form action="" method="POST" id="login_modal_form">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">登陆</h4>
              </div>
              <div class="modal-body">
                {% csrf_token %}
                {% for login in login_form %}
                    <label for="{{ login.id_for_label }}">{{ login.label }}</label>
                    {{ login }}
                {% endfor %}
                <span class="pull-left text-danger" id="login_modal_tip"></span>
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-primary">登陆</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
              </div>
            </form>
        </div>
      </div>
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        String.prototype.format = function () {
            var str = this;
            for (var i =0 ; i < arguments.length; i ++){
                var str = str.replace( new RegExp('\\{' + i + '\\}','g' ) , arguments[i])
            };
            return str
        };
        function likechange(obj,content_type,object_id) {
            var is_like = obj.getElementsByClassName("active");
            console.log('is_like:' + is_like);
            console.log('is_like:' + is_like.length);
            is_like = is_like.length == 0;
            console.log('is_like:' + is_like);
            {#$(this).first().toggleClass("active");#}
            $.ajax({
                url:"{% url 'likes:like_change' %}",
                type:"GET",
                data:{
                    content_type:content_type,
                    object_id:object_id,
                    is_like:is_like,
                },
                cache:false,
                success:function (data) {
                    if(data["status"] == "SUCCESS"){
                       // 更新点赞状态
                        var element = $(obj.getElementsByClassName('glyphicon'));
                        if(is_like){
                            element.addClass('active');
                        }else{
                            element.removeClass('active');
                        }
                        //更新点赞数量
                        $(obj.getElementsByClassName('like-num')).html(data["like_num"])
                    }else{
                        console.log(data["message"])
                        $("#login_model").modal("show")
                    }
                },
                errors:function (xhr) {
                    console.log(xhr,"123123123")
                }
            })

        };
        $("#comment-form").submit(function () {
            if (CKEDITOR.instances["id_text"].document.getBody().getText().trim() == '') {
                $("#comment_error").text('评论内容不能为空');
                return false;
            }
            ;
            {#更新数据到textarea#}
            CKEDITOR.instances["id_text"].updateElement()
            {#异步提交#}
            $.ajax({
                url: "{% url 'comment:update_coment' %}",
                type: "POST",
                data: $(this).serialize(),
                cache: false,
                success: function (data) {
                    if(data['reply_to'] == "-1"){
                        var html = ' <div class="conment-root" id="{0}">' +
                            '  <li >{1}({2})' +
                            '      : <div id="comment_{0}">{3}</div></li>' +
                            '  <a href="javascript:reply_comment({0})">回复</a>' +
                            '      <div class="like" onclick="likechange(this,\'comment\',{0})">' +
                            '          <span class="glyphicon glyphicon-thumbs-up btn " id="like-btn"></span>' +
                            '          <div class="like-num">0</div>' +
                            '      </div>' +
                           ' </div>';
                        var html = html.format(data['pk'],data['username'],data['comment_time'],data['text']);
                        console.log("11111")
                        $("#comment-list").append(html)
                    }
                    else{
                         var html = '<div class="comment-reply">\n' +
                             '              <li >{0}({1})\n' +
                             '                  回复 {3}(内容：{4})\n' +
                             '                  : <div id="comment_{5}">{6}</div></li>\n' +
                             '              <a href="javascript:reply_comment({5})"> 回复</a>\n' +
                             '               <div class="like" onclick="likechange(this,\'reply\',{5})">\n' +
                             '                  <span class="glyphicon glyphicon-thumbs-up btn " id="like-btn"></span>\n' +
                             '                  <div class="like-num" >0</div>\n' +
                             '              </div>\n' +
                             '       </div>';
                        var html = html.format(data['username'],data['comment_time'],data['text'],data["reply_to"],data["parent_text"],data["pk"],data["text"]);
                        console.log("22222")
                        console.log(data["root_pk"])
                        $("#" + data["root_pk"]).append(html);
                    }

                    {#清空编辑框的内容#}
                    CKEDITOR.instances["id_text"].setData("")
                    $("#comment_error").text('评论成功');
                },
                error: function (errors) {
                    console.log("xhr:" + errors);
                }
            });
            return false
        });

        function reply_comment(reply_comment_id) {
            console.log(reply_comment_id)
            // 设置值
            $("#reply_comment_id").val(reply_comment_id)
            html1 = $("#comment_" + reply_comment_id).html()
            $("#comment-reply-bk").html(html1);
            $("#content-reply-container").show();
            $("html").animate({scrollTop: $("#comment-form").offset().top - 140}, 300, function () {
                CKEDITOR.instances["id_text"].focus();
            })
        };
        $("#login_modal_form").submit(function (event) {
            {#防止form表单提交#}
            event.preventDefault();
            $.ajax({
                url:'{% url "user:login_for_modal" %}',
                type:"POST",
                data:$(this).serialize(),
                cache:false,
                success:function (data) {
                    if(data["status"] == "SUCCESS"){
                        {#刷新页面#}
                        window.location.reload()
                    }else{
                        $("#login_modal_tip").html("用户名或密码不正确")
                    }
                },
                errors:function () {
                    
                }
            });
        })
    </script>
{% endblock %}